### PR TITLE
feat: ggplot survival curves

### PR DESCRIPTION
**Pull request by ESCRI11**
Added the option to plot using ggplot (`survminer::ggsurvplot`) to obtain easier to read plots. Especially good for stratified survival analysis.

E.g.:

image

### CODE REVIEW

**Comment by neelsoumya** [comment]
Thanks @ESCRI11  can you please sync with the main branch and then resend this pull request. I am getting merge conflicts

**Comment by ESCRI11** [comment]
Synced with main branch. Now it should be ok

**Comment by neelsoumya** [comment]
Thanks @ESCRI11 ! 
great work! 
Could you please update the DESCRIPTION file also with an updated version number? e.g. 2.1.3

**Comment by neelsoumya** [comment]
thanks @ESCRI11 !

**Comment by StuartWheater** [comment]
**Results of devtools::check()**

❯ checking for portable file names ... WARNING
  Found the following file with a non-portable file name:
    dssurvival lay summary.pdf
  These are not fully portable file names.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
  Found the following non-portable file paths:
    dsSurvivalClient/tests/testthat/data_files/SURVIVAL/COLLAPSE_NO_MISSING/collapse_no_missing_study1.csv
    dsSurvivalClient/tests/testthat/data_files/SURVIVAL/COLLAPSE_NO_MISSING/collapse_no_missing_study2.csv
    dsSurvivalClient/tests/testthat/data_files/SURVIVAL/COLLAPSE_NO_MISSING/collapse_no_missing_study3.csv
  
  Tarballs are only required to store paths of up to 100 bytes and cannot
  store those of more than 256 bytes, with restrictions including to 100
  bytes for the final component.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.

❯ checking package subdirectories ... WARNING
  Invalid citation information in ‘inst/CITATION’:
    Error in bibentry(bibtype = entry, textVersion = textVersion, header = header,     footer = footer, ...): argument is missing, with no default

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'ds.plotsurvfit'
    ‘ggplot’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘readme.md’
  Package has no Sweave vignette sources and no VignetteBuilder field.

❯ checking for hidden files and directories ... NOTE
  Found the following hidden files and directories:
    .github
  These were most likely included in error. See section ‘Package
  structure’ in the ‘Writing R Extensions’ manual.

❯ checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    ‘LICENSE.md’ ‘dssurvival lay summary.pdf’

❯ checking dependencies in R code ... NOTE
  Namespaces in Imports field not imported from:
    ‘data.table’ ‘fields’ ‘gridExtra’ ‘survival’
    All declared Imports should be used.

**Review by neelsoumya — APPROVED** [review]

**Comment by neelsoumya** [comment]
thanks @ESCRI11 @StuartWheater

**Pull request merged**
